# Generated by Django 4.1.7 on 2023-04-19 07:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Marketing",
            fields=[
                (
                    "no",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("date", models.DateField(blank=True)),
                ("customer", models.CharField(max_length=100)),
                ("po_no", models.CharField(blank=True, max_length=100)),
                ("po_date", models.DateField(blank=True, null=True)),
                ("marketing_item", models.CharField(max_length=100)),
                ("consignee_tel_no", models.CharField(blank=True, max_length=100)),
                ("buyer_tel_no", models.CharField(blank=True, max_length=100)),
                ("payment_terms", models.CharField(blank=True, max_length=100)),
                ("paying_authority", models.CharField(blank=True, max_length=100)),
                ("penalty_clause", models.CharField(blank=True, max_length=100)),
                ("insurance", models.CharField(blank=True, max_length=100)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("delivery_place", models.CharField(blank=True, max_length=100)),
                ("mode_of_despatch", models.CharField(blank=True, max_length=100)),
                ("inspection", models.CharField(blank=True, max_length=100)),
                ("special_instruction", models.CharField(blank=True, max_length=100)),
                (
                    "despatch_additional_info",
                    models.CharField(blank=True, max_length=100),
                ),
                ("note", models.CharField(blank=True, max_length=100)),
                ("remarks", models.CharField(blank=True, max_length=100)),
                ("prr_no", models.CharField(blank=True, max_length=100)),
                ("prr_date", models.CharField(blank=True, max_length=100)),
                ("amount", models.CharField(blank=True, max_length=100)),
                ("mode_of_payment", models.CharField(blank=True, max_length=100)),
                ("purpose", models.CharField(blank=True, max_length=100)),
                ("prr_remark", models.CharField(blank=True, max_length=100)),
                ("billing_status", models.CharField(blank=True, max_length=100)),
                (
                    "dispatch_iniitial_date",
                    models.DateField(blank=True, default=datetime.date.today),
                ),
                (
                    "dispatch_iniitial_remarks",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "dispatch_iniitial_destination",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "dispatch_iniitial_transporter",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "dispatch_iniitial_packing",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "dispatch_iniitial_exp_time",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "dispatch_advanced_date",
                    models.DateField(blank=True, default=datetime.date.today),
                ),
                (
                    "dispatch_advanced_checkpost",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "dispatch_advanced_trns_lr_no",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "dispatch_advanced_trns_lr_date",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "dispatch_advanced_dc_no",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "dispatch_advanced_dc_date",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "dispatch_advanced_lr_no",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "dispatch_advanced_lr_date",
                    models.DateField(blank=True, default=datetime.date.today),
                ),
                (
                    "dispatch_advanced_vehicel_no",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "dispatch_advanced_remarks",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "packing_forwarding_charge",
                    models.CharField(blank=True, max_length=100),
                ),
                ("freight", models.CharField(blank=True, max_length=100)),
                ("sub_total", models.CharField(blank=True, max_length=100)),
                ("tax_gst", models.CharField(blank=True, max_length=100)),
                ("cess", models.CharField(blank=True, max_length=100)),
                ("grand_total", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "db_table": "marketing",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("si_no", models.IntegerField(blank=True)),
                ("is_std", models.BooleanField(blank=True)),
                ("item", models.CharField(blank=True, max_length=100)),
                ("rating", models.CharField(blank=True, max_length=100)),
                ("quantity", models.IntegerField(blank=True)),
                ("unit", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("wo_nos", models.CharField(blank=True, max_length=100)),
                (
                    "basic_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    "basic_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    "dp",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    "net_weight_per_unit",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    "gross_weight_per_unit",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    "total_weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                ("serial_nos", models.CharField(blank=True, max_length=100)),
                (
                    "item_group",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_query_name="item_group",
                        to="marketing.marketing",
                    ),
                ),
            ],
            options={
                "db_table": "item",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="addresss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("org", models.CharField(blank=True, max_length=255)),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("address_line_3", models.CharField(blank=True, max_length=255)),
                ("pin", models.CharField(blank=True, max_length=10)),
                ("phone_no", models.CharField(blank=True, max_length=15)),
                ("gst_no", models.CharField(blank=True, max_length=15)),
                ("type", models.CharField(blank=True, max_length=255)),
                ("telephone_no", models.CharField(blank=True, max_length=15)),
                (
                    "group",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_query_name="group",
                        to="marketing.marketing",
                    ),
                ),
            ],
            options={
                "db_table": "addresss",
                "managed": True,
            },
        ),
    ]
