# Generated by Django 4.1.7 on 2023-05-08 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Marketing",
            fields=[
                (
                    "no",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("customer", models.CharField(max_length=100, null=True)),
                ("po_no", models.CharField(blank=True, max_length=100, null=True)),
                ("po_date", models.DateField(blank=True, null=True)),
                ("marketing_item", models.CharField(max_length=100, null=True)),
                (
                    "consignee_tel_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "buyer_tel_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "payment_terms",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "paying_authority",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "penalty_clause",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("insurance", models.CharField(blank=True, max_length=100, null=True)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                (
                    "delivery_place",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mode_of_despatch",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("inspection", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "special_instruction",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "despatch_additional_info",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("note", models.CharField(blank=True, max_length=100, null=True)),
                ("remarks", models.CharField(blank=True, max_length=100, null=True)),
                ("prr_no", models.CharField(blank=True, max_length=100, null=True)),
                ("prr_date", models.CharField(blank=True, max_length=100, null=True)),
                ("amount", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "mode_of_payment",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("purpose", models.CharField(blank=True, max_length=100, null=True)),
                ("prr_remark", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "billing_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dispatch_iniitial_date", models.DateField(blank=True, null=True)),
                (
                    "dispatch_iniitial_remarks",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dispatch_iniitial_destination",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dispatch_iniitial_transporter",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dispatch_iniitial_packing",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dispatch_iniitial_exp_time",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dispatch_advanced_date", models.DateField(blank=True, null=True)),
                (
                    "dispatch_advanced_checkpost",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dispatch_advanced_trns_lr_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dispatch_advanced_trns_lr_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dispatch_advanced_dc_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dispatch_advanced_dc_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dispatch_advanced_lr_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dispatch_advanced_lr_date", models.DateField(blank=True, null=True)),
                (
                    "dispatch_advanced_vehicel_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dispatch_advanced_remarks",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "packing_forwarding_charge",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("freight", models.CharField(blank=True, max_length=100, null=True)),
                ("sub_total", models.CharField(blank=True, max_length=100, null=True)),
                ("tax_gst", models.CharField(blank=True, max_length=100, null=True)),
                ("cess", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "grand_total",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "marketing",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("si_no", models.IntegerField(blank=True, null=True)),
                ("is_std", models.BooleanField(blank=True, null=True)),
                ("item", models.CharField(blank=True, max_length=100, null=True)),
                ("rating", models.CharField(blank=True, max_length=100, null=True)),
                ("quantity", models.IntegerField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, max_length=100, null=True)),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                ("wo_nos", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "basic_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "basic_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "dp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "net_weight_per_unit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "gross_weight_per_unit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "total_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("serial_nos", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "item_group",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_query_name="item_group",
                        to="marketing.marketing",
                    ),
                ),
            ],
            options={
                "db_table": "item",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="addresss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("org", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "address_line_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_line_3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("pin", models.CharField(blank=True, max_length=10, null=True)),
                ("phone_no", models.CharField(blank=True, max_length=15, null=True)),
                ("gst_no", models.CharField(blank=True, max_length=15, null=True)),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "telephone_no",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "group",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_query_name="group",
                        to="marketing.marketing",
                    ),
                ),
            ],
            options={
                "db_table": "addresss",
                "managed": True,
            },
        ),
    ]
