# Generated by Django 4.1.7 on 2023-03-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='buyer_tel_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='consignee_tel_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='delivery_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='delivery_place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='despatch_additional_info',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='freight',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='inspection',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='insurance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='mode_of_despatch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='paying_authority',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='penalty_clause',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='po_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='remarks',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='special_instruction',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
