# Generated by Django 4.1.7 on 2023-03-11 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresss',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_query_name='group', to='marketing.marketing'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_query_name='item_group', to='marketing.marketing'),
        ),
    ]
