# Generated by Django 4.1.7 on 2023-05-06 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_alter_addresss_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresss',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_query_name='group', to='marketing.marketing'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_query_name='item_group', to='marketing.marketing'),
        ),
    ]
