# Generated by Django 4.1.7 on 2023-03-08 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0002_addresss_item_marketing_delete_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="marketing",
            options={"managed": True},
        ),
        migrations.RenameField(
            model_name="marketing",
            old_name="item",
            new_name="marketing_item",
        ),
        migrations.RemoveField(
            model_name="marketing",
            name="id",
        ),
        migrations.AddField(
            model_name="addresss",
            name="group",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="marketing.marketing",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="item_group",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="marketing.marketing",
            ),
        ),
        migrations.AlterField(
            model_name="marketing",
            name="no",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name="item",
            table="item",
        ),
        migrations.AlterModelTable(
            name="marketing",
            table="marketing",
        ),
    ]
