# Generated by Django 4.1.7 on 2023-03-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_addresss_item_marketing_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketing',
            name='id',
        ),
        migrations.AlterField(
            model_name='marketing',
            name='no',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
