# Generated by Django 4.1.7 on 2023-03-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_addresss_telephone_no_marketing_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresss',
            old_name='addr_line1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='addresss',
            old_name='addr_line2',
            new_name='address_line_2',
        ),
        migrations.RenameField(
            model_name='addresss',
            old_name='addr_line3',
            new_name='address_line_3',
        ),
        migrations.RenameField(
            model_name='marketing',
            old_name='mode_of_paymen',
            new_name='mode_of_payment',
        ),
        migrations.RenameField(
            model_name='marketing',
            old_name='prr_dat',
            new_name='prr_date',
        ),
        migrations.RenameField(
            model_name='marketing',
            old_name='prr_n',
            new_name='prr_no',
        ),
    ]
