# Generated by Django 4.1.7 on 2023-03-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_rename_addr_line1_addresss_address_line_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketing',
            name='cess',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='dispatch_advanced_checkpost',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='dispatch_advanced_date',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='dispatch_advanced_dc_date',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='dispatch_advanced_dc_no',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='dispatch_advanced_lr_date',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='dispatch_advanced_lr_no',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='dispatch_advanced_remarks',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='dispatch_advanced_trns_lr_date',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='dispatch_advanced_trns_lr_no',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='dispatch_advanced_vehicel_no',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='packing_forwarding_charge',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='tax_gst',
        ),
    ]
