# Generated by Django 4.1.7 on 2023-03-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_marketing_cess_marketing_dispatch_advanced_checkpost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='po_date',
            field=models.DateField(blank=True),
        ),
    ]
