# Generated by Django 4.1.7 on 2023-03-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_alter_marketing_date_alter_marketing_po_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='po_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
