# Generated by Django 4.1.7 on 2023-05-08 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bom",
            fields=[
                ("matcode", models.CharField(max_length=8)),
                ("qty", models.DecimalField(decimal_places=3, max_digits=8)),
                ("bpcode", models.CharField(max_length=8)),
                (
                    "bpmatcode",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "bom",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="MaterialList",
            fields=[
                (
                    "matcode",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(blank=True, max_length=45, null=True)),
                ("ref", models.CharField(blank=True, max_length=36, null=True)),
                ("au", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "safstk",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=15, null=True
                    ),
                ),
                (
                    "reorder",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=15, null=True
                    ),
                ),
                (
                    "ar",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=15, null=True
                    ),
                ),
                ("desk", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "ordcst",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "eoq",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=15, null=True
                    ),
                ),
                (
                    "lt",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=12, null=True
                    ),
                ),
                (
                    "safty",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=15, null=True
                    ),
                ),
                (
                    "auamt",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=15, null=True
                    ),
                ),
                (
                    "spare",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=15, null=True
                    ),
                ),
                ("gr", models.CharField(blank=True, max_length=4, null=True)),
                ("nm", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "pstock",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=15, null=True
                    ),
                ),
                (
                    "ind",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=15, null=True
                    ),
                ),
                (
                    "nsaftystk",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=15, null=True
                    ),
                ),
                ("specno", models.CharField(blank=True, max_length=10, null=True)),
                ("matgroup", models.CharField(blank=True, max_length=20, null=True)),
                ("section", models.CharField(blank=True, max_length=25, null=True)),
                ("group_b", models.CharField(blank=True, max_length=30, null=True)),
                ("group_c", models.CharField(blank=True, max_length=30, null=True)),
                ("group_a", models.CharField(blank=True, max_length=30, null=True)),
                ("abc", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "reordqty",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=13, null=True
                    ),
                ),
                (
                    "unitrate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("dwgno", models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                "db_table": "material_list",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Po",
            fields=[
                ("srlno", models.BigAutoField(primary_key=True, serialize=False)),
                ("pono", models.CharField(blank=True, max_length=10, null=True)),
                ("prno", models.BigIntegerField(blank=True, null=True)),
                ("poyear", models.CharField(blank=True, max_length=4, null=True)),
                ("matcode", models.CharField(blank=True, max_length=6, null=True)),
                ("ssrl", models.CharField(blank=True, max_length=2, null=True)),
                ("submited", models.BooleanField(default=False)),
                (
                    "poqty",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=17, null=True
                    ),
                ),
                ("podate", models.DateField(blank=True, null=True)),
                (
                    "porate",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=17, null=True
                    ),
                ),
                ("vender", models.CharField(blank=True, max_length=5, null=True)),
                ("remark", models.CharField(blank=True, max_length=50, null=True)),
                ("edate", models.DateField(blank=True, null=True)),
                ("enq_ref", models.CharField(blank=True, max_length=30, null=True)),
                ("off_ref", models.CharField(blank=True, max_length=30, null=True)),
                ("mrqdept", models.CharField(blank=True, max_length=7, null=True)),
                ("ex_dut", models.CharField(blank=True, max_length=10, null=True)),
                ("sal_tx", models.CharField(blank=True, max_length=10, null=True)),
                ("pandf", models.CharField(blank=True, max_length=10, null=True)),
                ("fright", models.CharField(blank=True, max_length=25, null=True)),
                ("delivery", models.CharField(blank=True, max_length=100, null=True)),
                ("p_terms", models.CharField(blank=True, max_length=100, null=True)),
                ("rmks", models.CharField(blank=True, max_length=100, null=True)),
                ("ord_acc", models.CharField(blank=True, max_length=20, null=True)),
                ("pri_vari", models.CharField(blank=True, max_length=100, null=True)),
                ("sup_grad", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "pandf1",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "pandfamt",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "ex_duty1",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "cst1",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "vat1",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("against", models.CharField(blank=True, max_length=15, null=True)),
                ("deldate", models.DateField(blank=True, null=True)),
                (
                    "srtx1",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("exdutyin", models.BooleanField(default=False)),
                ("pandfin", models.BooleanField(default=False)),
                ("sltaxin", models.CharField(blank=True, max_length=12, null=True)),
                ("postatus", models.CharField(blank=True, max_length=10, null=True)),
                ("postatusdate", models.DateField(blank=True, null=True)),
                (
                    "gst",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("gstin", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "po",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Polog",
            fields=[
                ("slno", models.BigAutoField(primary_key=True, serialize=False)),
                ("srlno", models.BigIntegerField(null=True)),
                ("pono", models.CharField(max_length=10)),
                ("prno", models.BigIntegerField()),
                ("matcode", models.CharField(max_length=6)),
                ("ssrl", models.CharField(max_length=2)),
                ("poqty", models.DecimalField(decimal_places=3, max_digits=17)),
                ("poyear", models.CharField(max_length=4)),
                ("podate", models.DateField()),
                ("porate", models.DecimalField(decimal_places=3, max_digits=17)),
                ("vender", models.CharField(max_length=5)),
                ("remark", models.CharField(max_length=50)),
                ("edate", models.DateField()),
                ("enq_ref", models.CharField(max_length=30)),
                ("off_ref", models.CharField(max_length=30)),
                ("mrqdept", models.CharField(max_length=7)),
                ("ex_dut", models.CharField(max_length=10)),
                ("sal_tx", models.CharField(max_length=10)),
                ("pandf", models.CharField(max_length=10)),
                ("fright", models.CharField(max_length=25)),
                ("delivery", models.CharField(max_length=100)),
                ("p_terms", models.CharField(max_length=100)),
                ("rmks", models.CharField(max_length=100)),
                ("ord_acc", models.CharField(max_length=20)),
                ("pri_vari", models.CharField(max_length=100)),
                ("sup_grad", models.CharField(max_length=20)),
                ("pandf1", models.DecimalField(decimal_places=3, max_digits=6)),
                ("pandfamt", models.DecimalField(decimal_places=3, max_digits=14)),
                ("ex_duty1", models.DecimalField(decimal_places=3, max_digits=6)),
                ("cst1", models.DecimalField(decimal_places=3, max_digits=6)),
                ("vat1", models.DecimalField(decimal_places=3, max_digits=6)),
                ("against", models.CharField(max_length=15)),
                ("deldate", models.DateField()),
                ("srtx1", models.DecimalField(decimal_places=3, max_digits=6)),
                ("exdutyin", models.BooleanField()),
                ("pandfin", models.BooleanField()),
                ("sltaxin", models.CharField(max_length=12)),
                ("postatus", models.CharField(max_length=10)),
                ("postatusdate", models.DateField()),
                ("logid", models.CharField(max_length=25)),
                ("eddt", models.DateField()),
                ("edtime", models.TimeField()),
                ("gst", models.DecimalField(decimal_places=2, max_digits=5)),
                ("gstin", models.BooleanField()),
            ],
            options={
                "db_table": "polog",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Prdetail",
            fields=[
                ("srlno", models.BigAutoField(primary_key=True, serialize=False)),
                ("prno", models.BigIntegerField(blank=True, null=True)),
                ("pono", models.CharField(blank=True, max_length=10, null=True)),
                ("pryear", models.CharField(blank=True, max_length=4, null=True)),
                ("matcode", models.CharField(blank=True, max_length=6, null=True)),
                ("ssrl", models.CharField(blank=True, max_length=2, null=True)),
                ("submited", models.BooleanField(blank=True, null=True)),
                (
                    "pr_qty",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=17, null=True
                    ),
                ),
                ("pr_date", models.DateField(blank=True, null=True)),
                ("rq_date", models.DateField(blank=True, null=True)),
                ("remark", models.CharField(blank=True, max_length=20, null=True)),
                ("podate", models.DateField(blank=True, null=True)),
                (
                    "poqty",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=17, null=True
                    ),
                ),
                ("supcode", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "porate",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=17, null=True
                    ),
                ),
                ("lpr", models.CharField(blank=True, max_length=10, null=True)),
                ("lprdt", models.DateField(blank=True, null=True)),
                (
                    "pr_pen",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=17, null=True
                    ),
                ),
                (
                    "stock",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=17, null=True
                    ),
                ),
                ("tpndr", models.CharField(blank=True, max_length=20, null=True)),
                ("apprsr1", models.CharField(blank=True, max_length=20, null=True)),
                ("apprsr2", models.CharField(blank=True, max_length=20, null=True)),
                ("apprsr3", models.CharField(blank=True, max_length=20, null=True)),
                ("apprsr4", models.CharField(blank=True, max_length=20, null=True)),
                ("apprsr5", models.CharField(blank=True, max_length=20, null=True)),
                ("apprsr6", models.CharField(blank=True, max_length=20, null=True)),
                ("apprsr7", models.CharField(blank=True, max_length=20, null=True)),
                ("apprsr8", models.CharField(blank=True, max_length=20, null=True)),
                ("apprsr9", models.CharField(blank=True, max_length=20, null=True)),
                ("apprsr10", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "pndpo",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=17, null=True
                    ),
                ),
                (
                    "ratehike",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                ("sugg", models.CharField(blank=True, max_length=25, null=True)),
                ("wor1", models.CharField(blank=True, max_length=10, null=True)),
                ("wor2", models.CharField(blank=True, max_length=10, null=True)),
                ("wor3", models.CharField(blank=True, max_length=10, null=True)),
                ("wor4", models.CharField(blank=True, max_length=10, null=True)),
                ("wor5", models.CharField(blank=True, max_length=10, null=True)),
                ("wo5r", models.CharField(blank=True, max_length=10, null=True)),
                ("prremark", models.CharField(blank=True, max_length=250, null=True)),
                ("itremark", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "prdetail",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "productid",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("ssrl", models.CharField(blank=True, max_length=2, null=True)),
                ("submited", models.BooleanField(blank=True, null=True)),
                ("productname", models.CharField(blank=True, max_length=50, null=True)),
                ("db", models.BooleanField(blank=True, null=True)),
                ("saeid", models.CharField(blank=True, max_length=5, null=True)),
                ("taxid", models.CharField(blank=True, max_length=5, null=True)),
                ("model", models.CharField(blank=True, max_length=15, null=True)),
                ("netwt", models.CharField(blank=True, max_length=10, null=True)),
                ("grosswt", models.CharField(blank=True, max_length=10, null=True)),
                ("partno", models.CharField(blank=True, max_length=15, null=True)),
                ("standard", models.BooleanField(blank=True, null=True)),
                ("bpcode", models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                "db_table": "product",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "work_order_no",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_query_name="work_order_no",
                        serialize=False,
                        to="marketing.marketing",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "THE MARKETING DEPARTMENT APPROVED"),
                            (2, "PLANNING DEPARMENT ISSUED A WARNING"),
                            (3, "PLANNING DEPARMENT HAS REJECTED THE ORDER"),
                        ],
                        default=1,
                    ),
                ),
            ],
            options={
                "db_table": "status",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "matcode",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="planning.materiallist",
                    ),
                ),
                (
                    "qty",
                    models.DecimalField(
                        blank=True, decimal_places=3, default=0, max_digits=15
                    ),
                ),
                (
                    "safe_stock",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=15),
                ),
            ],
            options={
                "db_table": "stock",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Stock_log",
            fields=[
                (
                    "qty",
                    models.DecimalField(
                        blank=True, decimal_places=3, default=0, max_digits=15
                    ),
                ),
                (
                    "Add_or_Consumed",
                    models.CharField(
                        choices=[
                            ("ADDED", "ADDED TO THE STOCK "),
                            ("CONSUMED", "TAKEN FROM STOCK"),
                        ],
                        max_length=20,
                    ),
                ),
                ("Date", models.DateField(blank=True)),
                ("gnr_no", models.CharField(blank=True, max_length=40, null=True)),
                ("snr_no", models.CharField(blank=True, max_length=40, null=True)),
                ("remark", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "transaction_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "matcode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planning.materiallist",
                    ),
                ),
            ],
            options={
                "db_table": "stock_log",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Prdetaillog",
            fields=[
                ("slno", models.BigAutoField(primary_key=True, serialize=False)),
                ("srlno", models.IntegerField(blank=True, null=True)),
                ("prno", models.BigIntegerField(blank=True, null=True)),
                ("pono", models.CharField(blank=True, max_length=10, null=True)),
                ("pryear", models.CharField(blank=True, max_length=4, null=True)),
                ("matcode", models.CharField(blank=True, max_length=6, null=True)),
                ("ssrl", models.CharField(blank=True, max_length=2, null=True)),
                ("submited", models.BooleanField(blank=True, null=True)),
                (
                    "pr_qty",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=17, null=True
                    ),
                ),
                ("pr_date", models.DateField(blank=True, null=True)),
                ("rq_date", models.DateField(blank=True, null=True)),
                ("remark", models.CharField(blank=True, max_length=20, null=True)),
                ("podate", models.DateField(blank=True, null=True)),
                (
                    "poqty",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=17, null=True
                    ),
                ),
                ("supcode", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "porate",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=17, null=True
                    ),
                ),
                ("lpr", models.CharField(blank=True, max_length=10, null=True)),
                ("lprdt", models.DateField(blank=True, null=True)),
                (
                    "pr_pen",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=17, null=True
                    ),
                ),
                (
                    "stock",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=17, null=True
                    ),
                ),
                ("tpndr", models.CharField(blank=True, max_length=20, null=True)),
                ("apprsr1", models.CharField(blank=True, max_length=20, null=True)),
                ("apprsr2", models.CharField(blank=True, max_length=20, null=True)),
                ("apprsr3", models.CharField(blank=True, max_length=20, null=True)),
                ("apprsr4", models.CharField(blank=True, max_length=20, null=True)),
                ("apprsr5", models.CharField(blank=True, max_length=20, null=True)),
                ("apprsr6", models.CharField(blank=True, max_length=20, null=True)),
                ("apprsr7", models.CharField(blank=True, max_length=20, null=True)),
                ("apprsr8", models.CharField(blank=True, max_length=20, null=True)),
                ("apprsr9", models.CharField(blank=True, max_length=20, null=True)),
                ("apprsr10", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "pndpo",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=17, null=True
                    ),
                ),
                (
                    "ratehike",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                ("sugg", models.CharField(blank=True, max_length=25, null=True)),
                ("wor1", models.CharField(blank=True, max_length=10, null=True)),
                ("wor2", models.CharField(blank=True, max_length=10, null=True)),
                ("wor3", models.CharField(blank=True, max_length=10, null=True)),
                ("wor4", models.CharField(blank=True, max_length=10, null=True)),
                ("wor5", models.CharField(blank=True, max_length=10, null=True)),
                ("wo5r", models.CharField(blank=True, max_length=10, null=True)),
                ("prremark", models.CharField(blank=True, max_length=250, null=True)),
                ("itremark", models.CharField(blank=True, max_length=50, null=True)),
                ("logid", models.CharField(blank=True, max_length=25, null=True)),
                ("eddt", models.DateField(blank=True, null=True)),
                ("edtime", models.TimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "prdetaillog",
                "managed": True,
                "unique_together": {("slno", "srlno")},
            },
        ),
    ]
