# Generated by Django 4.1.7 on 2023-03-16 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing', '0002_alter_marketing_buyer_tel_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'THE MARKETING DEPARTMENT APPROVED'), (2, 'PLANNING DEPARMENT ISSUED A WARNING'), (3, 'PLANNING DEPARMENT HAS REJECTED THE ORDER')], default=1)),
                ('work_order_no', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_query_name='work_order_no', to='marketing.marketing')),
            ],
        ),
    ]
