# Generated by Django 4.1.7 on 2023-05-06 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_alter_addresss_group_alter_item_item_group'),
        ('planning', '0002_prdetail_alter_polog_options_alter_polog_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='work_order_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_query_name='work_order_no', serialize=False, to='marketing.marketing'),
        ),
    ]
