# Generated by Django 4.1.7 on 2023-03-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_alter_status_options_alter_status_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('matcode', models.CharField(max_length=8)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=8)),
                ('bpcode', models.CharField(max_length=8)),
                ('bpmatcode', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialList',
            fields=[
                ('matcode', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
                ('ref', models.CharField(blank=True, max_length=36, null=True)),
                ('au', models.CharField(blank=True, max_length=2, null=True)),
                ('safstk', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('reorder', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('ar', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('desk', models.CharField(blank=True, max_length=5, null=True)),
                ('ordcst', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('eoq', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('lt', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('safty', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('auamt', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('spare', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('gr', models.CharField(blank=True, max_length=4, null=True)),
                ('nm', models.CharField(blank=True, max_length=1, null=True)),
                ('pstock', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('ind', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('nsaftystk', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('specno', models.CharField(blank=True, max_length=10, null=True)),
                ('matgroup', models.CharField(blank=True, max_length=20, null=True)),
                ('section', models.CharField(blank=True, max_length=25, null=True)),
                ('group_b', models.CharField(blank=True, max_length=30, null=True)),
                ('group_c', models.CharField(blank=True, max_length=30, null=True)),
                ('group_a', models.CharField(blank=True, max_length=30, null=True)),
                ('abc', models.CharField(blank=True, max_length=2, null=True)),
                ('reordqty', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('unitrate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dwgno', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'material_list',
                'managed': False,
            },
        ),
    ]
