# Generated by Django 4.1.7 on 2023-05-11 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_alter_stock_log_gnr_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_log',
            old_name='gnr_no',
            new_name='grn_no',
        ),
    ]
