# Generated by Django 4.1.7 on 2023-05-19 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_rename_gnr_no_stock_log_grn_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Po',
        ),
        migrations.DeleteModel(
            name='Polog',
        ),
    ]
