# Generated by Django 4.1.7 on 2023-03-30 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_bom_materiallist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bom',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='materiallist',
            options={'managed': True},
        ),
    ]
