# Generated by Django 4.1.7 on 2023-06-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0004_delete_po_delete_polog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="status",
            name="status",
        ),
        migrations.AddField(
            model_name="status",
            name="design_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="status",
            name="marketing_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="status",
            name="planning_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="status",
            name="production_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="status",
            name="purchase_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
