# Generated by Django 4.1.7 on 2023-03-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_alter_bom_options_alter_materiallist_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ssrl', models.CharField(blank=True, max_length=2, null=True)),
                ('submited', models.BooleanField(blank=True, null=True)),
                ('productname', models.CharField(blank=True, max_length=50, null=True)),
                ('db', models.BooleanField(blank=True, null=True)),
                ('saeid', models.CharField(blank=True, max_length=5, null=True)),
                ('taxid', models.CharField(blank=True, max_length=5, null=True)),
                ('model', models.CharField(blank=True, max_length=15, null=True)),
                ('netwt', models.CharField(blank=True, max_length=10, null=True)),
                ('grosswt', models.CharField(blank=True, max_length=10, null=True)),
                ('partno', models.CharField(blank=True, max_length=15, null=True)),
                ('standard', models.BooleanField(blank=True, null=True)),
                ('bpcode', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': True,
            },
        ),
    ]
