# Generated by Django 4.1.7 on 2023-04-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
