# Generated by Django 4.1.7 on 2023-06-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0005_remove_status_status_status_design_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="design_status",
            field=models.CharField(
                blank=True, default="Not started", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="marketing_status",
            field=models.CharField(
                blank=True, default="Not started", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="planning_status",
            field=models.CharField(
                blank=True, default="Not started", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="production_status",
            field=models.CharField(
                blank=True, default="Not started", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="purchase_status",
            field=models.CharField(
                blank=True, default="Not started", max_length=20, null=True
            ),
        ),
    ]
