# Generated by Django 4.1.7 on 2023-04-03 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_alter_item_basic_amount_alter_item_basic_rate_and_more'),
        ('planning', '0006_delete_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('work_order_no', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_query_name='work_order_no', serialize=False, to='marketing.marketing')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'THE MARKETING DEPARTMENT APPROVED'), (2, 'PLANNING DEPARMENT ISSUED A WARNING'), (3, 'PLANNING DEPARMENT HAS REJECTED THE ORDER')], default=1)),
            ],
            options={
                'db_table': 'Status',
                'managed': True,
            },
        ),
    ]
