# Generated by Django 4.1.7 on 2023-04-03 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_alter_item_basic_amount_alter_item_basic_rate_and_more'),
        ('planning', '0007_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='work_order_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_query_name='work_order_no', serialize=False, to='marketing.marketing'),
        ),
    ]
