# Generated by Django 4.1.7 on 2023-04-03 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_alter_status_work_order_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('matcode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='planning.materiallist')),
                ('qty', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15)),
                ('safe_stock', models.DecimalField(blank=True, decimal_places=3, max_digits=15)),
            ],
            options={
                'db_table': 'stock',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Stock_log',
            fields=[
                ('qty', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15)),
                ('Add_or_Cosumed', models.CharField(choices=[('ADDED', 'ADDED TO THE STOCK '), ('CONSUMED', 'TAKEN FROM STOCK')], max_length=20)),
                ('Date', models.DateField(blank=True)),
                ('gnr_no', models.CharField(blank=True, max_length=40)),
                ('snr_no', models.CharField(blank=True, max_length=40)),
                ('remark', models.CharField(blank=True, max_length=100)),
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('matcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.materiallist')),
            ],
            options={
                'db_table': 'stock_log',
                'managed': True,
            },
        ),
    ]
