# Generated by Django 4.1.7 on 2023-04-09 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0010_alter_status_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_log',
            old_name='Add_or_Cosumed',
            new_name='Add_or_Consumed',
        ),
    ]
