# Generated by Django 4.1.7 on 2023-04-09 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0012_alter_stock_log_date_alter_stock_log_gnr_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_log',
            name='Date',
            field=models.DateField(default=datetime.datetime(2023, 4, 9, 1, 23, 33, 415864, tzinfo=datetime.timezone.utc)),
        ),
    ]
