# Generated by Django 4.1.7 on 2023-04-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0016_alter_stock_log_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Po",
            fields=[
                ("srlno", models.BigAutoField(primary_key=True, serialize=False)),
                ("pono", models.CharField(blank=True, max_length=10, null=True)),
                ("prno", models.BigIntegerField(blank=True, null=True)),
                ("poyear", models.CharField(blank=True, max_length=4, null=True)),
                ("matcode", models.CharField(blank=True, max_length=6, null=True)),
                ("ssrl", models.CharField(blank=True, max_length=2, null=True)),
                ("submited", models.BooleanField(default=False)),
                (
                    "poqty",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=17, null=True
                    ),
                ),
                ("podate", models.DateField(blank=True, null=True)),
                (
                    "porate",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=17, null=True
                    ),
                ),
                ("vender", models.CharField(blank=True, max_length=5, null=True)),
                ("remark", models.CharField(blank=True, max_length=50, null=True)),
                ("edate", models.DateField(blank=True, null=True)),
                ("enq_ref", models.CharField(blank=True, max_length=30, null=True)),
                ("off_ref", models.CharField(blank=True, max_length=30, null=True)),
                ("mrqdept", models.CharField(blank=True, max_length=7, null=True)),
                ("ex_dut", models.CharField(blank=True, max_length=10, null=True)),
                ("sal_tx", models.CharField(blank=True, max_length=10, null=True)),
                ("pandf", models.CharField(blank=True, max_length=10, null=True)),
                ("fright", models.CharField(blank=True, max_length=25, null=True)),
                ("delivery", models.CharField(blank=True, max_length=100, null=True)),
                ("p_terms", models.CharField(blank=True, max_length=100, null=True)),
                ("rmks", models.CharField(blank=True, max_length=100, null=True)),
                ("ord_acc", models.CharField(blank=True, max_length=20, null=True)),
                ("pri_vari", models.CharField(blank=True, max_length=100, null=True)),
                ("sup_grad", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "pandf1",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "pandfamt",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "ex_duty1",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "cst1",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "vat1",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("against", models.CharField(blank=True, max_length=15, null=True)),
                ("deldate", models.DateField(blank=True, null=True)),
                (
                    "srtx1",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("exdutyin", models.BooleanField(default=False)),
                ("pandfin", models.BooleanField(default=False)),
                ("sltaxin", models.CharField(blank=True, max_length=12, null=True)),
                ("postatus", models.CharField(blank=True, max_length=10, null=True)),
                ("postatusdate", models.DateField(blank=True, null=True)),
                (
                    "gst",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("gstin", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "po",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Polog",
            fields=[
                ("slno", models.BigAutoField(primary_key=True, serialize=False)),
                ("srlno", models.BigIntegerField(null=True)),
                ("pono", models.CharField(max_length=10)),
                ("prno", models.BigIntegerField()),
                ("matcode", models.CharField(max_length=6)),
                ("ssrl", models.CharField(max_length=2)),
                ("poqty", models.DecimalField(decimal_places=3, max_digits=17)),
                ("poyear", models.CharField(max_length=4)),
                ("podate", models.DateField()),
                ("porate", models.DecimalField(decimal_places=3, max_digits=17)),
                ("vender", models.CharField(max_length=5)),
                ("remark", models.CharField(max_length=50)),
                ("edate", models.DateField()),
                ("enq_ref", models.CharField(max_length=30)),
                ("off_ref", models.CharField(max_length=30)),
                ("mrqdept", models.CharField(max_length=7)),
                ("ex_dut", models.CharField(max_length=10)),
                ("sal_tx", models.CharField(max_length=10)),
                ("pandf", models.CharField(max_length=10)),
                ("fright", models.CharField(max_length=25)),
                ("delivery", models.CharField(max_length=100)),
                ("p_terms", models.CharField(max_length=100)),
                ("rmks", models.CharField(max_length=100)),
                ("ord_acc", models.CharField(max_length=20)),
                ("pri_vari", models.CharField(max_length=100)),
                ("sup_grad", models.CharField(max_length=20)),
                ("pandf1", models.DecimalField(decimal_places=3, max_digits=6)),
                ("pandfamt", models.DecimalField(decimal_places=3, max_digits=14)),
                ("ex_duty1", models.DecimalField(decimal_places=3, max_digits=6)),
                ("cst1", models.DecimalField(decimal_places=3, max_digits=6)),
                ("vat1", models.DecimalField(decimal_places=3, max_digits=6)),
                ("against", models.CharField(max_length=15)),
                ("deldate", models.DateField()),
                ("srtx1", models.DecimalField(decimal_places=3, max_digits=6)),
                ("exdutyin", models.BooleanField()),
                ("pandfin", models.BooleanField()),
                ("sltaxin", models.CharField(max_length=12)),
                ("postatus", models.CharField(max_length=10)),
                ("postatusdate", models.DateField()),
                ("logid", models.CharField(max_length=25)),
                ("eddt", models.DateField()),
                ("edtime", models.TimeField()),
                ("gst", models.DecimalField(decimal_places=2, max_digits=5)),
                ("gstin", models.BooleanField()),
            ],
            options={
                "db_table": "bhelksgd.polog",
            },
        ),
    ]
